server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: joabfg
    password: joabfg
security:
  jwt:
    token:
      secret-key: chave_microservices
      expire-length: 36000